DocumentRoot {{ webserver_default_site_document_root }}

{% if webserver_use_awstats %}
RewriteRule ^/awstats/$ /cgi-bin/awstats.pl?config=%{HTTP_HOST} [redirect=permanent,last]
<Location /cgi-bin/awstats.pl>
    AuthType {{ webserver_default_site_awstats_auth_type }}
    AuthName "Awstats"
    {{ webserver_default_site_awstats_extra_config }}
    {% if webserver_default_site_awstats_auth_type == "Basic" %}
    AuthUserFile /etc/{{ webserver_webserver_dirname }}/awstats-global.htpasswd
    {% endif %}
    Require user {% for user in webserver_default_site_awstats_users %}{{ user.username }} {% endfor +%}
</Location>
Alias /awstats-icon/ /usr/share/awstats/icon/
{% endif %}

{{ webserver_default_site_extras }}
