---
- name: Restart web server
  ansible.builtin.service:
    name: "{{ webserver_webserver_dirname }}"
    state: restarted

- name: Reload web server
  ansible.builtin.service:
    name: "{{ webserver_webserver_dirname }}"
    state: reloaded
