# 301 redirects should not be cached, because while a website is being built
# and moved from a dev to a production server, a 301 temporary redirect is
# often used. The safest thing is to prevent the cache to save the redirection,
# even if it is declared as permanent.
Header set Cache-Control no-cache env=REDIRECT_STATUS

# Add VHost to log format
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
