server {
    listen 80 default_server;
    listen [::]:80 default_server;
    {% if website_force_ssl -%}
    return 302 https://{{ website_domain }}$request_uri;
    {% else %}
    return 404;
    {% endif %}
}

server {
    listen              443 ssl default_server;
    listen              [::]:443 ssl default_server;
    ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    gzip                off;  # Avoid CRIME exploit

    return 404;
}
