---
- name: Install Postfix
  ansible.builtin.apt:
    name:
      - postfix

- name: Setup /etc/mailname
  ansible.builtin.copy:
    content: "{{ mailname }}"
    dest: /etc/mailname
    mode: '0644'
  notify:
    - Reload Postfix

- name: Configure Postfix
  ansible.builtin.template:
    src: main.cf
    dest: /etc/postfix/main.cf
    mode: '0644'
  notify:
    - Reload Postfix

- name: Setup authentication
  ansible.builtin.template:
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: '0600'
  when: smarthostusername | length > 0
  notify:
    - Compile sasl_passwd

- name: Start Postfix
  ansible.builtin.service:
    name: postfix
    state: started

- name: Set virtual aliases
  ansible.builtin.lineinfile:
    path: /etc/postfix/virtual
    create: true
    regexp: "^{{ item.key }}@"
    line: "{{ item.key }}@{{ mailname }} {{ item.value }}"
    mode: '0644'
  loop: "{{ mail_aliases | dict2items }}"
  notify:
    - Postmap aliases
