#!/usr/sbin/nft -f

destroy table inet aptiko

table inet aptiko {
    chain input {
        type filter hook input priority filter; policy drop;

        ct state invalid drop
        ct state established,related accept
        iif lo accept

        include "/etc/nftables/ansible-early.nft"

        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

{% set ssh_ipv4 = ssh_allowed_ip_addresses | select('search', '^[^:]+$') | list %}
{% set ssh_ipv6 = ssh_allowed_ip_addresses | select('search', ':') | list %}
{% if ssh_allowed_ip_addresses %}
{% if ssh_ipv4 %}
        ip saddr { {{ ssh_ipv4 | join(', ') }} } tcp dport {{ ssh_port }} accept
{% endif %}
{% if ssh_ipv6 %}
        ip6 saddr { {{ ssh_ipv6 | join(', ') }} } tcp dport {{ ssh_port }} accept
{% endif %}
{% else %}
        tcp dport {{ ssh_port }} accept
{% endif %}

        include "/etc/nftables/ansible-late.nft"
    }

    chain output {
        type filter hook output priority filter; policy accept;

        ct state established,related accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        ct state invalid drop
        ct state established,related accept
    }
}
