---
- name: Reload ssh
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Import firewall handlers
  ansible.builtin.import_tasks: firewall.yml

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Reboot
  ansible.builtin.reboot:
