---
- name: Install node repo prerequisites
  apt:
    name:
     - gnupg
     - apt-transport-https

- name: Get node apt key
  shell:
    cmd: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
    creates: /usr/share/keyrings/nodesource.gpg

- name: Determine dpkg architecture for node
  command: dpkg --print-architecture
  register: get_architecture
  check_mode: no
  ignore_errors: yes
  changed_when: false

- name: Add node apt repository
  apt_repository:
    repo: "deb [arch={{ get_architecture.stdout }} signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
    filename: nodesource

- name: Install nodejs
  apt:
    name: nodejs
