---
- name: Install node repo prerequisites
  apt:
    name:
     - gnupg
     - apt-transport-https

- name: Get node apt key
  shell:
    cmd: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
    creates: /usr/share/keyrings/nodesource.gpg

- name: Determine dpkg architecture for node
  command: dpkg --print-architecture
  register: get_architecture
  check_mode: no
  ignore_errors: yes
  changed_when: false

- name: Add node apt repository
  apt_repository:
    repo: "deb [arch={{ get_architecture.stdout }} signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
    filename: nodesource

- name: Get installed nodejs version
  command:
    argv:
      - dpkg-query
      - --show
      - "--showformat=${Version}"
      - nodejs
  register: installed_nodejs_version
  check_mode: no
  failed_when: false
  changed_when: false

- name: Install nodejs  # noqa package-latest
  apt:
    name: nodejs
    state: >-
      {{
        'present'
        if installed_nodejs_version.rc == 0
        and installed_nodejs_version.stdout is match(
          '^(?:[0-9]+:)?' ~ (node_version | string) ~ '\.'
        )
        else 'latest'
      }}
