Include "/etc/awstats/awstats.conf"
SiteDomain="{{ website_domain }}"
{% if website_domain_aliases_without_redirect is defined %}
HostAliases="{{ website_domain_aliases_without_redirect|join(" ") }}"
{% endif %}
DirData="/var/lib/awstats/{{ website_domain }}"
