---
- name: Uninstall firewall packages we don't want
  ansible.builtin.apt:
    name:
      - ferm
      - ufw
    state: absent

- name: Install nftables
  ansible.builtin.apt:
    name: nftables

- name: Remove ferm configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/ferm
    - /etc/default/ferm

- name: Create /etc/nftables
  ansible.builtin.file:
    state: directory
    dest: /etc/nftables
    mode: "0755"

- name: Create file /etc/nftables/ansible-early.nft
  ansible.builtin.copy:
    dest: /etc/nftables/ansible-early.nft
    force: false
    content: ""
    mode: "0644"

- name: Create file /etc/nftables/ansible-late.nft
  ansible.builtin.copy:
    dest: /etc/nftables/ansible-late.nft
    force: false
    content: ""
    mode: "0644"

- name: Set nftables.conf
  ansible.builtin.template:
    src: nftables.conf
    dest: /etc/nftables.conf
    mode: "0644"
  notify: Reload nftables

- name: Start nftables at boot
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: started

- name: Allow Prometheus through firewall
  ansible.builtin.blockinfile:
    path: /etc/nftables/ansible-late.nft
    marker: "# {mark} ANSIBLE MANAGED BLOCK prometheus"
    block: |
      {% set prometheus_ipv4 = prometheus_server_ips.split() | select('search', '^[^:]+$') | list %}
      {% set prometheus_ipv6 = prometheus_server_ips.split() | select('search', ':') | list %}
      {% if prometheus_ipv4 %}
      ip saddr { {{ prometheus_ipv4 | join(', ') }} } tcp accept
      {% endif %}
      {% if prometheus_ipv6 %}
      ip6 saddr { {{ prometheus_ipv6 | join(', ') }} } tcp accept
      {% endif %}
  notify: Reload nftables
  when: prometheus_server_ips | default('') | length > 0
