---
- name: Create Aptiko state directory
  ansible.builtin.file:
    path: /var/lib/aptiko.general
    state: directory
    mode: "0755"

- name: Check if base initialization is complete
  ansible.builtin.stat:
    path: /var/lib/aptiko.general/base-initialized
  register: base_initialized

- name: Check legacy base initialization marker
  ansible.builtin.stat:
    path: /etc/ferm/ansible-early
  register: legacy_base_initialized

- name: Update and upgrade if this is a new server
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when:
    - not base_initialized.stat.exists
    - not legacy_base_initialized.stat.exists
  notify: Reboot

- name: Mark base initialization complete
  ansible.builtin.copy:
    content: ""
    dest: /var/lib/aptiko.general/base-initialized
    force: false
    mode: "0644"

- name: Check if tmp.mount exists
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/tmp.mount
  register: tmp_mount_unit

- name: Do not use tmpfs for /tmp
  ansible.builtin.systemd:
    name: tmp.mount
    masked: true
    enabled: false
    daemon_reload: true
  when:
    - base_disable_tmpfs_for_tmp
    - tmp_mount_unit.stat.exists
  notify: Reboot

- name: Reboot if needed
  ansible.builtin.meta: flush_handlers

- name: Validate base_unattended_upgrades
  ansible.builtin.assert:
    that: base_unattended_upgrades in ["present", "absent", "ignore"]
    fail_msg: base_unattended_upgrades must be "present", "absent", or "ignore"

- name: Install or uninstall unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: "{{ base_unattended_upgrades }}"
  when: base_unattended_upgrades != "ignore"

- name: Validate base_sudo
  ansible.builtin.assert:
    that: base_sudo in ["present", "absent", "ignore"]
    fail_msg: base_sudo must be "present", "absent", or "ignore"

- name: Install or uninstall sudo
  ansible.builtin.apt:
    name: sudo
    state: "{{ base_sudo }}"
  when: base_sudo != "ignore"

- name: Validate base_ntpsec
  ansible.builtin.assert:
    that: base_ntpsec in ["present", "absent", "ignore"]
    fail_msg: base_ntpsec must be "present", "absent", or "ignore"

- name: Install or uninstall ntpsec
  ansible.builtin.apt:
    name: ntpsec
    state: "{{ base_ntpsec }}"
  when: base_ntpsec != "ignore"

- name: Install common apt packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - debian-goodies

- name: Install locales package
  ansible.builtin.apt:
    name: locales
    state: present
  when: base_locales | length > 0

- name: Install locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ base_locales }}"

- name: Configure ssh
  ansible.builtin.import_tasks: ssh.yml

- name: Validate base_journald_forward_to_syslog
  ansible.builtin.assert:
    that: base_journald_forward_to_syslog in ["yes", "no", "ignore"]
    fail_msg: base_journald_forward_to_syslog must be "yes", "no", or "ignore"

- name: Configure systemd-journald
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: ForwardToSyslog
    value: "{{ base_journald_forward_to_syslog }}"
    no_extra_spaces: true
    create: false
  when: base_journald_forward_to_syslog != "ignore"
  notify: Restart journald

# Node exporter

- name: Install node-exporter
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
  when: base_prometheus_server_ips | default('') | length > 0

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml
  when: base_setup_firewall

- name: Update and check for reboots
  ansible.builtin.import_tasks: update.yml
  tags:
    - never
    - update
