---
- name: Configure certbot
  ansible.builtin.template:
    owner: root
    mode: "0600"
    src: apache/certbot-credentials-cloudflare.ini
    dest: /etc/letsencrypt/certbot-credentials-cloudflare.ini

- name: Ensure firewall allows certbot
  ansible.builtin.meta: flush_handlers
  when: base_setup_firewall | default(false)

- name: Install letsencrypt certificate
  ansible.builtin.command:
    argv:
      - certbot
      - certonly
      - --non-interactive
      - --agree-tos
      - --dns-cloudflare
      - --dns-cloudflare-credentials
      - /etc/letsencrypt/certbot-credentials-cloudflare.ini
      - --cert-name
      - "{{ webserver_default_site_letsencrypt_domain | regex_replace('^\\*\\.', '') }}"
      - -m
      - "{{ webserver_letsencrypt_admin }}"
      - -d
      - "{{ webserver_default_site_letsencrypt_domain }}"
    creates: "/etc/letsencrypt/live/{{ webserver_default_site_letsencrypt_domain | regex_replace('^\\*\\.', '') }}/fullchain.pem"
