---

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Restart prometheus-mysqld-exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
  when: prometheus_server_ips|default(False)
