---
- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Restart prometheus-postgres-exporter
  service:
    name: prometheus-postgres-exporter
    state: restarted
